### ISSUE TITLE
Question: Does this only run from github?

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Documentation#6]
I'm assuming that this documentation will only run if it is thru the GitHub pages?
When I try running it thru my local machine (a Mac) it doesn't work right.
It needs the built-in GitHub stuff?

I tried setting the link to "https//tonejaco.github.io/Documentation/" on my branch and it doesn't work. Don't understand why.

**Comment by tonejaco** [comment]
Ok. I discovered http://127.0.0.1:4000/Documentation/   
Works now.

**Comment by parachvte** [comment]
> I tried setting the link to "https//tonejaco.github.io/Documentation/" on my branch and it doesn't work. Don't understand why.

You need to set Github Pages on your repo settings.
