### ISSUE TITLE
Getting Error...

### ISSUE THREAD

**Issue by tonejaco** [Snapmaker/Documentation#7]
In the terminal window when ever I make changes to the source:

/Users/tonyjaco/Documents/GitHub/Documentation/vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated

A LOT of them.

**Comment by parachvte** [comment]
It's Jekyll's code didn't adopt to ruby 2.7.
I think that use older ruby (like 2.5.0) the warning will disappear.

**Comment by tonejaco** [comment]
Ok, thanks.
